### ISSUE TITLE
Is there a possibility to add parameters cotaining spaces

### ISSUE THREAD

**Issue by skelsec** [KimiNewt/aiocmd#1]
Hello,

currently I'm struggling with using a `do_get` function which takes a path as input.
Since the path contains spaces, aiocmd just splits the path into two.

Question: is there a way to add quotes which would force input values with spaces to be treated as a single parameter?

**Comment by KimiNewt** [comment]
Solved in 6508f48e50adedaf824f113293fc20d020bd7a7e
