### ISSUE TITLE
possibility for decorators

### ISSUE THREAD

**Issue by skelsec** [KimiNewt/aiocmd#2]
So, I tried to add a decorator for my function. Resulted in error.
Is there a (good) way to do it?

**Comment by KimiNewt** [comment]
It doesn't work because if you wrap the function in a decorator it (by default) hides its parameters and will only show the decorators. This can be solved by using `functools.wraps` (which is recommended anyway). Like so:
```python
def deco(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print("deco")
        return func(*args, **kwargs)
    return wrapper
```
